image: gitpod/workspace-java-17

tasks:
  - init: mvn install -DskipTests=false

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven
    - vscjava.vscode-java-test
